apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy.yaml
  - hpa.yaml
  - pdb.yaml
  - virtualservice.yaml
  - destinationrule.yaml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: score-api
      app.kubernetes.io/part-of: Commerce
      app.kubernetes.io/managed-by: ohanyere-idp
      platform.ohanyere.io/template: template-node-api
      finops.ohanyere.io/cost-center: commerce
  - includeSelectors: false
    includeTemplates: true
    pairs:
      platform.io/team: Commerce
      platform.io/cost-center: commerce
images:
  - name: kuberpull/score-api
    newName: kuberpull/score-api
    newTag: dev
